    CREATE TABLE IF NOT EXISTS users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        name VARCHAR NOT NULL,
        email VARCHAR NOT NULL,
        CONSTRAINT pk_user PRIMARY KEY(id),
        CONSTRAINT UQ_USER_EMAIL UNIQUE(email)
    );

    CREATE TABLE IF NOT EXISTS categories (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        name VARCHAR,
        CONSTRAINT pk_category PRIMARY KEY(id),
        CONSTRAINT UQ_CATEGORY UNIQUE(name)
    );

    CREATE TABLE IF NOT EXISTS events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        annotation VARCHAR NOT NULL,
        category BIGINT NOT NULL,
        description VARCHAR NOT NULL,
        event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        paid BOOLEAN DEFAULT (false),
        participant_limit int DEFAULT (0),
        request_moderation BOOLEAN DEFAULT (true),
        title VARCHAR NOT NULL,
        initiator BIGINT NOT NULL,
        state VARCHAR(30) NOT NULL,
        published_on TIMESTAMP WITHOUT TIME ZONE,
        created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        is_available boolean DEFAULT (true),
        CONSTRAINT pk_event PRIMARY KEY(id),
        FOREIGN KEY (category) REFERENCES categories (id) ON DELETE CASCADE,
        FOREIGN KEY (initiator) REFERENCES users (id) ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS compilations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        pinned boolean,
        title VARCHAR,
        CONSTRAINT pk_compilation PRIMARY KEY(id)
    );

    CREATE TABLE IF NOT EXISTS compilations_events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        compilation_id BIGINT NOT NULL,
        event_id BIGINT NOT NULL,
        CONSTRAINT pk_compilation_event PRIMARY KEY(id),
        FOREIGN KEY (compilation_id) REFERENCES compilations (id),
        FOREIGN KEY (event_id) REFERENCES events (id)
    );

    CREATE TABLE IF NOT EXISTS requests (
        created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        event BIGINT NOT NULL,
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        requester BIGINT NOT NULL,
        state VARCHAR(30),
        CONSTRAINT pk_request PRIMARY KEY(id),
        FOREIGN KEY (requester) REFERENCES users (id) ON DELETE CASCADE,
        FOREIGN KEY (event) REFERENCES events (id) ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS likes (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        user_id INT NOT NULL,
        event_id INT NOT NULL,
        is_like BOOLEAN NOT NULL,
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
        FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
    );