    CREATE TABLE IF NOT EXISTS users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        name VARCHAR(255) NOT NULL,
        email VARCHAR(512) NOT NULL,
        CONSTRAINT pk_user PRIMARY KEY(id),
        CONSTRAINT UQ_USER_EMAIL UNIQUE(email)
        );

    CREATE TABLE IF NOT EXISTS categories (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        name VARCHAR(255),
        CONSTRAINT pk_category PRIMARY KEY(id),
        CONSTRAINT UQ_CATEGORY UNIQUE(name)
    );

    CREATE TABLE IF NOT EXISTS events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        annotation VARCHAR(255) NOT NULL,
        category BIGINT NOT NULL,
        description VARCHAR(1000) NOT NULL,
        event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        paid BOOLEAN DEFAULT (false),
        participant_limit int DEFAULT (0),
        request_moderation BOOLEAN DEFAULT (true),
        title VARCHAR(100) NOT NULL,
        initiator BIGINT NOT NULL,
        state VARCHAR(30) NOT NULL,
        published_on TIMESTAMP WITHOUT TIME ZONE,
        created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        is_available boolean DEFAULT (true),
        CONSTRAINT pk_event PRIMARY KEY(id),
        CONSTRAINT UQ_TITLE UNIQUE(title),
        FOREIGN KEY (category) REFERENCES categories (id) ON DELETE CASCADE,
        FOREIGN KEY (initiator) REFERENCES users (id) ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS complications (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        pinned boolean,
        title VARCHAR(120),
        CONSTRAINT pk_complication PRIMARY KEY(id)
    );

    CREATE TABLE IF NOT EXISTS complications_events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        complication_id BIGINT NOT NULL,
        event_id BIGINT NOT NULL,
        CONSTRAINT pk_complication_event PRIMARY KEY(id),
        FOREIGN KEY (complication_id) REFERENCES complications (id),
        FOREIGN KEY (event_id) REFERENCES events (id)
    );

    CREATE TABLE IF NOT EXISTS requests (
        created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        event BIGINT NOT NULL,
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        requester BIGINT NOT NULL,
        state VARCHAR(30),
        CONSTRAINT pk_request PRIMARY KEY(id),
        FOREIGN KEY (requester) REFERENCES users (id) ON DELETE CASCADE,
        FOREIGN KEY (event) REFERENCES events (id) ON DELETE CASCADE
    );