spring:
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true

    show-sql: true

  sql:
    init:
      mode: always

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

logging:
  level:
    org:
      springframework:
        orm.jpa: info
        orm.jpa.JpaTransactionManager: debug
        web.client.RestTemplate: debug
        transaction: info
        interceptor: trace

server:
  port: 9090

---
spring:
  config:
    activate:
      on-profile: "ci, test"

  datasource:
    url: jdbc:h2:mem:ewm-stat-service
    driver-class-name: org.h2.Driver
    username: test
    password: test

  h2:
    console:
      enabled: true