CREATE TABLE IF NOT EXISTS stats
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR(500)                            NOT NULL,
    uri       VARCHAR(500)                            NOT NULL,
    ip        VARCHAR(50)                             NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_stats PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS hits
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app         VARCHAR(500)                            NOT NULL,
    uri         VARCHAR(500)                            NOT NULL,
    hits        BIGINT                                  NOT NULL,
    unique_hits BIGINT                                  NOT NULL,
    CONSTRAINT pk_hits PRIMARY KEY (id)
);